// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxcxmegxplthzrmwbeps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4Y3htZWd4cGx0aHpybXdiZXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODI1NTksImV4cCI6MjA4NTM1ODU1OX0.md7HPEL1xeNHgz7Fxf30pNZzb4WPQoPjF9r1Hd9DpPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});